config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'
  resources :users, :only => [:new, :create, :index]
  resources :wines, :only => [:new, :create, :index]

  get '/login' => 'session#new' #login form
  post '/login' => 'session#create' #perform a log in
  delete '/login' => 'session#destroy' #log out
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :bigint(8)        not null, primary key
#  email      :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ApplicationRecord
  has_secure_password
  validates :email, :presence => true, :uniqueness => true
  has_and_belongs_to_many :wines
end

app/models/wine.rb
class Wine < ApplicationRecord

has_and_belongs_to_many :users

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

before_action :fetch_user

private
  def fetch_user
    #set up @current_user once someone has lgged in
    @current_user = User.find_by :id => session[:user_id] if session[:user_id].present?
    session[:user_id] = nil unless @current_user.present? #this prevents horros when reseeding

  end

  def check_for_login
    redirect_to login_path unless @current_user.present?
  end

    def check_for_admin
      redirect_to login_path unless (@current_user.present? && @current_user.admin?)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

def create
  user = User.find_by :email => params[:email]
  if user.present? && user.authenticate(params[:password])
  session[:user_id] = user.id
  redirect_to root_path
else
  flash[:error] = "invalid login"
  redirect_to login_path
end
  end

def destroy
  session[:user_id] = nil
  redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :check_for_ad, :only => [:index]

def index
  @users = User.all
end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
    session[:user_id] = @user.id
    redirect_to root_path #redirect to home if account avlid
  else
    render :new #or let them try again on for
  end
end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

end

app/controllers/wines_controller.rb
class WinesController < ApplicationController

def index
  @wines = Wine.all
end

#new
def new
  @wine = Wine.new
end

def show
    @wine = Wine.find params[:id]
  end


  #create - allows the user to post their wines
  def create
    wine = Wine.new
    wine.color = params[:color]
    wine.name = params[:name]
    wine.region = params[:region]
    wine.image = params[:image]
    wine.save
    redirect_to wines_path
  end


  def edit
    @wine = Wine.find params[:id]
  end

  def post
    wine = Wine.find params[:id]
    wine.color = params[:color]
    wine.name = params[:name]
    wine.region = params[:region]
    wine.image = params[:image]
  redirect_to wines_path
  end

  #delete
  def destroy
    @wine = Wine.find params[:id]
    @wine.destroy
    redirect_to wines_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vino</title>
    <link rel="stylesheet" href="/css/main.css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <%= link_to 'home', root_path %>
      <% if @current_user.present? %>
      <%= link_to 'email addresses', users_path if @current_user.admin? %>
      <%= link_to "sign out #{ @current_user.email }", login_path, :method => 'delete' %>
      <% else %>
      <%= link_to 'sign up', new_user_path %>
      <%= link_to 'sign in', login_path %>
     
      <% end %>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>

<% if @current_user.present? %>
<h1>welcome back  <%= @current_user.email %></h1>
<% end %>

<nav><%= link_to 'All wines', wines_path %></nav>
 <nav><%= link_to 'new wine', new_wine_path %></nav>

app/views/session/new.html.erb
<h1>Log in</h1>
<h2><%= flash[:error] %></h2>
<%= form_tag login_path do %>
<%= label_tag :email %>
<%= email_field_tag :email %>

<%= label_tag :password %>
<%= password_field_tag :password %>
<%= submit_tag "Log-in" %>

<% end %>
<nav><%= link_to 'All wines', wines_path %></nav>
 <nav><%= link_to 'new wine', new_wine_path %></nav>

app/views/users/index.html.erb
<h1>all users: <%= number_to_human User.count %></h1>

<% @users.each do |user| %>

<p><%=  user.email %></p>

<% end %>

<nav><%= link_to 'All wines', wines_path %></nav>
 <nav><%= link_to 'new wine', new_wine_path %></nav>

app/views/users/new.html.erb
<h1>sign up</h1>

<% if @user.errors.any? %>
<ol>
  <% @user.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ol>
<% end %>

<%= form_for @user do |f| %>
  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>



  <%= f.submit "sign up!" %>
<% end %>

<nav><%= link_to 'All wines', wines_path %></nav>
 <nav><%= link_to 'new wine', new_wine_path %></nav>

app/views/wines/_form.html.erb
<%= form_for @wine do |f| %>
<%= f.label :color %>
<%= f.text_field :color %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :region %>
<%= f.text_field :region %>
<%= f.label :image %>
<%= f.text_field :image %>

<%= f.submit %>
<% end %>

app/views/wines/edit.html.erb
<h1>wines</h1>

<%= render :partial => 'form' %>

app/views/wines/index.html.erb
<h1> vino varietals </h1>



<% @wines.each do |wine| %>
  <p>
    <a href="/wines/<%= wine["id"] %>">
  <%= wine['wine_type'] %>
</a>
</p>

  <% end %>

app/views/wines/new.html.erb
<h1>wines</h1>

<%= render :partial => 'form' %>

<nav><%= link_to 'All wines', wines_path %></nav>
 <nav><%= link_to 'new wine', new_wine_path %></nav>

app/views/wines/wines_show.erb
<h1><%= @wine.title %></h1>

<%= image_tag @wine.image, :alt => @wine.title, :class => 'feature' %>

<ul>

  <li><%= @wine.title %></li>
  <% if @wines.wine.present? %>
  <li>Wines: <%= link_to @wines.wine.name, @wines.wine %></li>
  <% end %>
  <li>color <%= @wine.color %></li>
  <li> region <%= @wine.region %></li>
  <li>image <%= @wine.image %></li>

</ul>
<div class="controls">
  <%= link_to "edit wines", edit_wine_path(@wines) %>
  <%= link_to 'delete wines', wine_path(@wines), :method => 'delete', :data => {:confirm => 'are you sure?'} %>
</div>

<nav><%= link_to 'All wines', wines_path %></nav>
 <nav><%= link_to 'new wine', new_wine_path %></nav>